name: Delete tags
on:
  schedule:
    - cron:  '30 1,10 * * *'
  workflow_dispatch:

jobs:
  delete_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Delete tags
        uses: massmutual/swift-gh-composite-actions/actions/delete-tag@v1.0.0
        with:
          github_token: ${{ github.token }}
          #Specify as a number followed by a unit of time (e.g., "10 days", "5 weeks",  "3 months", "2 years", etc.)
          #Delete tags if it is more than KEEP_TAGS_PERIOD
          keep_tags_period: "12 months"
          #Only deletes tags that contain a specified input string in the tag name
          #Enter strings seperated by comma , list of input strings are case insensitive 
          tag_names_contains: "beta,feature"
