name: Update Tag
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - run: echo ${{ steps.get_version.outputs.version-without-v }}

      - name: Update Confluence
        uses: massmutual/swift-gh-composite-actions/swift/release_confluence_update@v1
        with:
          conf_user: ${{ secrets.conf_user }}
          conf_token: ${{ secrets.conf_token }}
          repo_name: ${{ github.event.repository.name }}
          tag: ${{ steps.get_version.outputs.version-without-v }}


### Repo Name: Created by event in github action
### Tag: output of step with id: tag
### Save confluence token and username in repository secrets
